export const styles = {
  footer: {
    backgroundColor: "#374051",
    color: "#FFFFFF",
    paddingTop: "20px",
    minHeight: "40vh",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  top: {
    display: "flex",
    alignItems: "top",
    justifyContent: "start",
    flex: "wrap",
    padding: "0 80px",
  },
  option: { marginRight: "100px" },
  bottom: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flex: "wrap",
    color: "#FFFFFF",
    borderTop: "1px solid white",
    padding: "0 80px",
  },
  icon: {
    color: "#FFFFFF",
  },
  socialIcons: {
    display: "flex",
    alignItems: "top",
    justifyContent: "center",
  },
  iconContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff33",
    borderRadius: "50%",
    height: "2rem",
    width: "2rem",
    margin: "2px",
  },
};
