export const styles = {
  supportedPlatforms: { margin: "35px 0" },
  h1: {
    textAlign: "center",
    color: "#70A0FA",
    fontSize: "2rem",
    fontWeight: "700",
    marginBottom: "15px",
  },
  platform: {
    width: "12rem",
    border: "1.5px solid #F4F5F6",
    borderRadius: "10px",
    background: "#FFFFFF",
    boxShadow: " 12px 12px 35px rgba(0, 0, 0, 0.35)",
    padding: "5px",
  },
  platformContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    padding: "5px 25px 10px 5px",
  },
  supPlatforms: {
    display: "flex",
    justifyContent: "space-around",
    flex: "wrap",
    alignItems: "center",
    marginBottom: "40px",
  },
  switch: {
    width: "100%",
    display: "flex",
    justifyContent: "end",
    padding: 0,
  },
  icon: { color: "white", fontSize: "2rem" },
  iconContainer: {
    width: "3rem",
    height: "3rem",
    backgroundColor: "#2f89ce",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    marginRight: "5px",
    padding: "0",
  },
  platformName: { marginLeft: "5px", fontSize: "14px" },
  onOff: { color: "#808080", fontWeight: "bold" },
};
